apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: my-demo-config
  literals:
    - MY_NAMESPACE=banderle1-dev
    - MY_SANDBOX_ID=.apps.sandbox-m3.1530.p1.openshiftapps.com

secretGenerator:
- name: mastodon-api
  literals:
    - access-token=sha256~HS3K9RScdw24wjIX_UKH3VpBQwVqszJg_twWpbqqe0c

vars:
- name: MY_NAMESPACE
  objref:
    kind: ConfigMap
    name: my-demo-config
    apiVersion: v1
  fieldref:
    fieldpath: data.MY_NAMESPACE
- name: MY_SANDBOX_ID
  objref:
    kind: ConfigMap
    name: my-demo-config
    apiVersion: v1
  fieldref:
    fieldpath: data.MY_SANDBOX_ID

patchesStrategicMerge:
  - emoji-tracker.yaml
  - emoji-dashboard.yaml

configurations:
  - transformer_config.yaml

generatorOptions:
  disableNameSuffixHash: true
